### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by FQ400**
Hey @zanettin 

I got the following error when using `withState`

screenshot10

An dependency update to latest inferno (3.0.3) fixed the issue for me.
Based on the #5 the version in the `package.json`should be `0.0.12`. I didn't changed it because I don't known if there are tools involved.

Do you need more infos?

### CODE REVIEW

**Comment by zanettin** [comment]
Thanks a lot for your PR 😄 
I'm a bit surprised that the `dist/pure.js` files is missing the `.length` call since `dist` is just the babel transpiled output of the files in `src`... Maybe there's an issue with the babel plugin? Can you have a look on that as well? All files in `dist` gets overwritten on each publish so this change wont persist for long 😢

**Comment by FQ400** [comment]
I did the following:`npm run test`, `npm run lint` and `npm run build`. I added an `.nvmrc` with the node version `7.8.0`. All tests are green.

Investigating ...

**Comment by FQ400** [comment]
... done.

Now I did a full dependency update. `yarn outdated` or `npm outdated` are now returning nothing, which means everything is up to date.

All tests are green and the linter is ok.

The following packages were removed, because I think they were not used. At least I couldn't find a reference using `grep`:
- `enzyme`
- `inferno-create-element`

Regarding the generated changes of `createVNode` in:
- `createEagerElementUtil.js`
- `nest.js`

The change was introduced with [`babel-inferno-plugin 3.1.0`](https://github.com/infernojs/babel-plugin-inferno/releases/tag/3.1.0).

Regarding `pure.js` and `keys.length`. I actually don't know what happened there. But I think that wasn't working. See screenshot.

screen shot 2017-04-11 at 16 19 47

So far. Do you have more tests that I can rely on? @zanettin

**Comment by zanettin** [comment]
hi thx a lot @FQ400 !
just tried a re-build locally and the `.length` was always there. have no idea why this got lost on the last build.

**Comment by FQ400** [comment]
😄  Nice. Waiting for the publish.

**Comment by zanettin** [comment]
published => 0.0.13 👍 
thx again for your help!!

**Pull request merged**
